package similarityMetrics

type SIMILARITY_CHECK_METRIC string

const (
	COSINE_SIMILARITY   SIMILARITY_CHECK_METRIC = "cosine"
	EUCLIDEAN_DISTANCE  SIMILARITY_CHECK_METRIC = "euclidean"
	MANHATTAN_DISTANCE  SIMILARITY_CHECK_METRIC = "manhattan"
	MINKOWSKI_DISTANCE  SIMILARITY_CHECK_METRIC = "minkowski"
	PEARSON_CORRELATION SIMILARITY_CHECK_METRIC = "pearson"
)
